### ISSUE TITLE
Catalogar lista bibliográfica inicial

### ISSUE THREAD

**Issue by msampaio** [GenosResearchGroup/ContourMetrics#5]
## Descrição ##
Catalogar as entradas da lista de bibliografia inicial em formato bibtex.

Preencher corretamente as entradas no bibtex. Se possível, colocar um link para o arquivo de cada entrada.
Observar que há diversos itens repetidos.
Não se preocupar em baixar os arquivos, pois a lista ainda passará por uma triagem.

É necessário finalizar essa tarefa para seguir com a tarefa #4.

## Material ##
. Dados de entrada: bibliografia-inicial.html (Drobpox, pasta Produção)
. Onde guardar: arquivo.bib (Dropbox, pasta Produção)
. O que usar: pasta particular no Mendeley ou ferramenta online como http://truben.no/latex/bibtex/

**Comment by msampaio** [comment]
@AlissonGSilva, qual o estado da tarefa?

**Comment by AlissonGSilva** [comment]
@msampaio  como eu exporto pra .bib no Mendeley?
Testei o outro bibtex e so aparece um código, copia ele num texto e muda pra .bib?

**Comment by AlissonGSilva** [comment]
Acho que já entendi, li isso aqui;

 http://blog.mendeley.com/tipstricks/howto-use-mendeley-to-create-citations-using-latex-and-bibtex/

http://www.inf.ufes.br/~vitorsouza/blog/manage-your-bibliography-with-mendeley-and-bibtex/

To pensando que ele exportasse um arquivo só com todos os artigos que listei, mas parece que é um por um, é isso?

**Comment by msampaio** [comment]
No Mendeley desktop selecione os itens, clique com o botão direito e exporte para bibtex. Ele gera um arquivo com as entradas selecionadas.

**Comment by AlissonGSilva** [comment]
Marcos to tentando terminar logo esse aqui, é muita coisa. Ainda temos tempo??

**Comment by AlissonGSilva** [comment]
Marcos to tentando terminar logo esse aqui, é muita coisa. Ainda temos tempo??

**Comment by msampaio** [comment]
@AlissonGSilva, siga em frente com a tarefa. Preciso filtrar todos esses papers até o fim do mês. Se tiver que baixar o arquivo e cadastrar o bibtex de cada item que seleciono não terei como finalizar minha tarefa (#4) a tempo.

**Comment by AlissonGSilva** [comment]
Alguns eu já consigo achar na próprio Mendely, outros eu tenho que pesquisar o ano e em que lugar foi publicado, página  e etc, ae demora um pouco.

**Comment by msampaio** [comment]
Ok, mas revise as entradas do Mendeley, bem como do Google Scholar. É comum aparecer errado. O erro mais comum é conference proceedings como journal article

**Comment by msampaio** [comment]
@AlissonGSilva, já concluí a triagem da lista bibliográfica inicial. Essa tarefa caducou.
