### ISSUE TITLE
Baixar arquivos de papers

### ISSUE THREAD

**Issue by msampaio** [GenosResearchGroup/ContourMetrics#6]
Baixar os artigos abaixo.
Guardar na pasta Contour Metrics/Papers, no Dropbox.
Documentar aqui os arquivos não disponíveis.
Esta tarefa é necessária para a conclusão da tarefa #4.

http://www.tandfonline.com/doi/abs/10.1080/17459737.2014.935816#.VJV82sAMA
http://www.tandfonline.com/doi/abs/10.1080/08145857.1997.10415974#.VNDwA1XF_DI

http://www.tandfonline.com/doi/full/10.1080/17459737.2012.694715#.VNIAioVfs7A
http://link.springer.com/chapter/10.1007/978-3-319-11472-9_2
http://link.springer.com/chapter/10.1007/978-3-540-75134-2_8
http://www.tandfonline.com/doi/abs/10.1080/09298210500236325#.VNJjc1XF_DJ
http://www.tandfonline.com/doi/abs/10.1080/02643294.2012.707122#.VNJkQ1XF_DI

**Comment by msampaio** [comment]
@AlissonGSilva, qual o estado da tarefa?

**Comment by AlissonGSilva** [comment]
Consegui baixar 3 artigos, vou procurar mais um pouco. Os que achei estão já no Dropbox.

**Comment by msampaio** [comment]
@AlissonGSilva, liste aqui os que ficaram pendentes para eu fechar a tarefa.

**Comment by AlissonGSilva** [comment]
Faltam os:

Automatic species counterpoint composition by means of the dominance relation - Komosinski M, Szachewicz P

*A bibliography of statistical applications in musicology - Nigel Nettheim   
(Achei uma página do próprio autor, que parece ser o artigo, não sei se está completo, vou salvar em HTML e deixar no dropbox).

Thinking music with precision, depth, and passion - Guerino Mazzola

The Role of Statistics in Computational Musicology - Soubhik Chakraborty, Guerino Mazzola, Swarima Tewari, Moujhuri Patra

**Comment by msampaio** [comment]
Ótimo, @AlissonGSilva. Os dois últimos são os mais importantes. Veja se consegue encontrar em algum lugar.

**Comment by msampaio** [comment]
@AlissonGSilva, onde você guardou os Bibtex dos 3 papers que conseguiu?

**Comment by AlissonGSilva** [comment]
@msampaio  olhe lá em produção o arquivo que tem lá "My colection paper tarefa #6" , tem um dos artigos em html, você não quer que registre ele também? O do Nettheim?

**Comment by msampaio** [comment]
Ótimo, @AlissonGSilva. Descartei o Bonn da lista.
